server:
  port: ":8081"

database:
  driver: fake

log:
  level: debug

services:
  authn:
    url: "http://localhost:8082"
  authz:
    url: "http://localhost:8083"
  audit:
    url: "http://localhost:8085"

preflight:
  enabled: false
