server:
  port: ":8085"

database:
  driver: postgres
  host: localhost
  port: 5432
  user: dev
  password: dev
  database: ticked
  schema: audit
  sslmode: disable

nats:
  url: "nats://localhost:4222"
