server:
  port: ":8082"

services:
  authn:
    url: "http://localhost:8080"
  ticked:
    url: "http://localhost:8084"

auth:
  session:
    name: "ticked_session"
    ttl: "24h"

log:
  level: "info"
  format: "text"
